// Template only. The real config.js is generated by scripts/build-config.py
// from .env locally, or from repo Secrets in the GitHub Actions deploy.
// Do not fill this file in directly — put your values in .env instead.
window.CONFIG = {
  CLIENT_ID: 'REPLACE_WITH_OAUTH_CLIENT_ID.apps.googleusercontent.com',
  API_KEY: 'REPLACE_WITH_API_KEY',
  SHEET_NAME_PREFIX: 'PlaceTracker',
  ADMIN_CONTACT: 'dominic.critchlow@fractional.ai',
};
