#!/usr/bin/env python3
"""Generate config.js from .env (local) or process env (CI).

Usage:
  python3 scripts/build-config.py           # reads .env from repo root
  python3 scripts/build-config.py --env     # reads from process env (used by CI)
"""
import json
import os
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent


def parse_dotenv(text: str) -> dict:
    out = {}
    for line in text.splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        key, _, val = s.partition("=")
        key = key.strip()
        val = val.strip()
        if len(val) >= 2 and val[0] == val[-1] and val[0] in ("'", '"'):
            val = val[1:-1]
        out[key] = val
    return out


def main() -> int:
    use_env = "--env" in sys.argv
    if use_env:
        src = dict(os.environ)
    else:
        env_path = ROOT / ".env"
        if not env_path.exists():
            print(
                ".env not found. Copy .env.example to .env and fill in your values, "
                "or pass --env to use process environment (CI).",
                file=sys.stderr,
            )
            return 1
        src = parse_dotenv(env_path.read_text())

    required = ["PINS_CLIENT_ID", "PINS_API_KEY"]
    missing = [k for k in required if not src.get(k) or src[k].startswith("REPLACE_")]
    if missing:
        print(f"Missing or unfilled: {', '.join(missing)}", file=sys.stderr)
        return 1

    values = {
        "CLIENT_ID": src["PINS_CLIENT_ID"],
        "API_KEY": src["PINS_API_KEY"],
        "SHEET_NAME_PREFIX": src.get("PINS_SHEET_NAME_PREFIX") or "PlaceTracker",
        "ADMIN_CONTACT": src.get("PINS_ADMIN_CONTACT") or "",
    }

    body = (
        "// Generated by scripts/build-config.py — do not edit by hand.\n"
        "// Source of truth: .env (local) or GitHub Actions secrets (deploy).\n"
        "window.CONFIG = " + json.dumps(values, indent=2) + ";\n"
    )

    (ROOT / "config.js").write_text(body)
    print("Wrote config.js")
    return 0


if __name__ == "__main__":
    sys.exit(main())
